# Generated by Django 4.2.20 on 2026-09-26 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace_control', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspacemodel',
            name='archived_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Set when the user archives the space: hidden from the sidebar, nothing deleted. Opening the folder again clears it.', null=True),
        ),
    ]
