# Generated by Django 4.2.20 on 2026-09-21 05:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LlmProviderModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(choices=[('anthropic', 'Anthropic'), ('openai', 'OpenAI'), ('nvidia', 'NVIDIA NIM'), ('kimi', 'Kimi (Moonshot)')], help_text="Slug users store their API key under, e.g. 'anthropic'.", max_length=30, unique=True)),
                ('name', models.CharField(help_text='Human-friendly label shown in the app.', max_length=120)),
                ('api_style', models.CharField(choices=[('anthropic', 'Anthropic Messages API'), ('openai_compatible', 'OpenAI-compatible chat completions')], max_length=30)),
                ('api_url', models.URLField(help_text='Base API URL.')),
                ('default_model', models.CharField(help_text='Model id used when the caller does not name one.', max_length=120)),
                ('model_ids', models.JSONField(blank=True, default=list, help_text="Known model ids offered in the model picker, e.g. ['claude-sonnet-5'].")),
                ('priority', models.PositiveIntegerField(db_index=True, default=100, help_text='Lower runs first when the caller does not pin a provider.')),
                ('capabilities', models.JSONField(blank=True, default=list, help_text="What the provider supports, e.g. ['chat', 'json_output', 'tool_calling'].")),
                ('input_cost_per_million_usd', models.DecimalField(decimal_places=4, default=0, help_text="USD per 1,000,000 input tokens for the default model. 0 = don't cost calls.", max_digits=12)),
                ('output_cost_per_million_usd', models.DecimalField(decimal_places=4, default=0, help_text='USD per 1,000,000 output tokens for the default model.', max_digits=12)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'LLM Provider',
                'verbose_name_plural': 'LLM Providers',
                'db_table': 'ai_control_llm_providers',
                'ordering': ['priority', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='LlmApiCallModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(db_index=True, max_length=50)),
                ('model', models.CharField(blank=True, db_index=True, default='', max_length=120)),
                ('task_key', models.CharField(blank=True, db_index=True, default='', max_length=80)),
                ('trace_id', models.CharField(blank=True, db_index=True, max_length=120, null=True)),
                ('correlation_id', models.UUIDField(db_index=True, default=uuid.uuid4)),
                ('prompt_text', models.TextField()),
                ('prompt_metadata', models.JSONField(blank=True, null=True)),
                ('response_text', models.TextField(blank=True, null=True)),
                ('response_json', models.JSONField(blank=True, null=True)),
                ('input_tokens', models.IntegerField(blank=True, null=True)),
                ('output_tokens', models.IntegerField(blank=True, null=True)),
                ('total_tokens', models.IntegerField(blank=True, null=True)),
                ('latency_ms', models.IntegerField(blank=True, null=True)),
                ('cost_usd', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('status', models.CharField(choices=[('success', 'Success'), ('error', 'Error')], db_index=True, default='success', max_length=30)),
                ('error_type', models.CharField(blank=True, max_length=120, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='llm_api_calls', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'LLM API Call',
                'verbose_name_plural': 'LLM API Calls',
                'db_table': 'ai_control_llm_api_calls',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='ai_call_user_created_idx'), models.Index(fields=['provider', 'created_at'], name='ai_call_provider_created_idx'), models.Index(fields=['status', 'created_at'], name='ai_call_status_created_idx')],
            },
        ),
    ]
