# Generated by Django 4.2.20 on 2026-09-21 08:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('workspace_control', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ai_control', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentMessageModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seq', models.PositiveIntegerField(help_text='Position in the session transcript, from 0.')),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant')], max_length=20)),
                ('content', models.TextField(blank=True, default='')),
                ('stop_reason', models.CharField(blank=True, default='', max_length=40)),
                ('is_partial', models.BooleanField(default=False, help_text='True when the stream was cut before the model finished.')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('llm_call', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_messages', to='ai_control.llmapicallmodel')),
            ],
            options={
                'verbose_name': 'Agent Message',
                'verbose_name_plural': 'Agent Messages',
                'db_table': 'ai_control_agent_messages',
                'ordering': ['seq'],
            },
        ),
        migrations.CreateModel(
            name='AgentSessionModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('provider', models.CharField(blank=True, default='', help_text='Pinned provider slug, or empty for auto.', max_length=30)),
                ('model', models.CharField(blank=True, default='', help_text='Pinned model id, or empty for the provider default.', max_length=120)),
                ('task_key', models.CharField(db_index=True, default='agent', max_length=80)),
                ('system_prompt', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('idle', 'Idle'), ('running', 'Running'), ('awaiting_tools', 'Awaiting tool results'), ('error', 'Error')], db_index=True, default='idle', max_length=20)),
                ('running_since', models.DateTimeField(blank=True, null=True)),
                ('step_count', models.PositiveIntegerField(default=0, help_text='Model calls made so far.')),
                ('max_steps', models.PositiveIntegerField(default=50, help_text='Model calls allowed before the session stops.')),
                ('last_error', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_sessions', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_sessions', to='workspace_control.workspacemodel')),
            ],
            options={
                'verbose_name': 'Agent Session',
                'verbose_name_plural': 'Agent Sessions',
                'db_table': 'ai_control_agent_sessions',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='LlmToolModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.SlugField(help_text='Tool id the model calls and the client dispatches on.', max_length=60, unique=True)),
                ('label', models.CharField(help_text='Human-friendly label shown in the app.', max_length=120)),
                ('description', models.TextField(help_text='Sent to the model. Say what it does and when to use it.')),
                ('input_schema', models.JSONField(default=dict, help_text="JSON Schema (type: object) for the tool's arguments.")),
                ('risk', models.CharField(choices=[('read', 'Read only'), ('write', 'Writes files'), ('shell', 'Runs shell commands'), ('destructive', 'Destructive')], default='read', max_length=20)),
                ('executor', models.CharField(choices=[('client', 'Client (desktop)'), ('server', 'Server')], default='client', max_length=20)),
                ('priority', models.PositiveIntegerField(db_index=True, default=100, help_text='Order tools are listed to the model.')),
                ('task_keys', models.JSONField(blank=True, default=list, help_text="Task keys this tool is offered for, e.g. ['agent']. Empty = every task.")),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'LLM Tool',
                'verbose_name_plural': 'LLM Tools',
                'db_table': 'ai_control_llm_tools',
                'ordering': ['priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AgentToolCallModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('call_id', models.CharField(help_text='Provider-issued id; results are matched on it.', max_length=120)),
                ('name', models.CharField(db_index=True, max_length=60)),
                ('input', models.JSONField(default=dict)),
                ('risk', models.CharField(choices=[('read', 'Read only'), ('write', 'Writes files'), ('shell', 'Runs shell commands'), ('destructive', 'Destructive')], default='read', max_length=20)),
                ('seq_in_message', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('denied', 'Denied by user'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20)),
                ('output', models.TextField(blank=True, default='')),
                ('error', models.TextField(blank=True, default='')),
                ('duration_ms', models.IntegerField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tool_calls', to='ai_control.agentmessagemodel')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tool_calls', to='ai_control.agentsessionmodel')),
                ('tool', models.ForeignKey(blank=True, help_text='Null when the model asked for a name that is not registered.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calls', to='ai_control.llmtoolmodel')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Agent Tool Call',
                'verbose_name_plural': 'Agent Tool Calls',
                'db_table': 'ai_control_agent_tool_calls',
                'ordering': ['message__seq', 'seq_in_message'],
            },
        ),
        migrations.AddField(
            model_name='agentmessagemodel',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='ai_control.agentsessionmodel'),
        ),
        migrations.AddField(
            model_name='agentmessagemodel',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='agenttoolcallmodel',
            constraint=models.UniqueConstraint(fields=('session', 'call_id'), name='agent_tool_call_unique_id'),
        ),
        migrations.AddIndex(
            model_name='agentsessionmodel',
            index=models.Index(fields=['user', 'updated_at'], name='agent_session_user_upd_idx'),
        ),
        migrations.AddConstraint(
            model_name='agentmessagemodel',
            constraint=models.UniqueConstraint(fields=('session', 'seq'), name='agent_message_unique_seq'),
        ),
    ]
