# Generated by Django 4.2.20 on 2026-09-21 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_control', '0002_agent_loop'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentsessionmodel',
            name='device',
            field=models.JSONField(blank=True, default=dict, help_text='Client machine as reported at creation: os, os_version, arch, shell, locale, app_version.'),
        ),
    ]
