# Generated by Django 4.2.20 on 2026-09-21 17:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ai_control', '0003_agent_session_device'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentmessagemodel',
            name='skill',
            field=models.CharField(blank=True, default='', help_text='Name of the skill a user message invoked; its instructions are already spliced into content.', max_length=64),
        ),
        migrations.CreateModel(
            name='SkillModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.SlugField(help_text="Slash command id, e.g. 'review' for /review.", max_length=64)),
                ('description', models.CharField(blank=True, default='', help_text='One line shown in the picker.', max_length=500)),
                ('content', models.TextField(help_text='Markdown instructions sent to the model; front matter stripped.')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Skill',
                'verbose_name_plural': 'Skills',
                'db_table': 'ai_control_skills',
                'ordering': ['name'],
            },
        ),
        migrations.AddConstraint(
            model_name='skillmodel',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='skill_unique_user_name'),
        ),
    ]
