# Generated by Django 4.2.20 on 2026-09-25 06:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ai_control', '0004_skills'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillFileModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('path', models.CharField(help_text="Path inside the skill folder, e.g. 'references/api.md'.", max_length=255)),
                ('content', models.TextField()),
                ('size', models.PositiveIntegerField(help_text='Size in bytes as uploaded (UTF-8).')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='ai_control.skillmodel')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Skill file',
                'verbose_name_plural': 'Skill files',
                'db_table': 'ai_control_skill_files',
                'ordering': ['path'],
            },
        ),
        migrations.AddConstraint(
            model_name='skillfilemodel',
            constraint=models.UniqueConstraint(fields=('skill', 'path'), name='skill_file_unique_path'),
        ),
    ]
